<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Valerii Demidov
 * @category   Cdev
 * @package    Cdev_XPaymentsConnector
 * @copyright  (c) Qualiteam Software Ltd. <info@qtmsoft.com>. All rights reserved.
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
$xpayUrlMas =  parse_url(Mage::getModel('xpaymentsconnector/payment_cc')->getConfig('xpay_url'));
$xpayUrl =  $xpayUrlMas["scheme"]."://".$xpayUrlMas["host"];
$updateCartUrl = Mage::getUrl("checkout/cart",array("unset_xp_prepare_order"=>1));
$checkIframeUrl = Mage::getUrl('xpaymentsconnector/processing/istokenactual', array('_nosid' => true,'_secure'=>true));
?>

<button type="submit" title="<?php echo $this->__('Place Order') ?>" class="button btn-checkout" onclick="submitXpaymentIframe('<?php echo $checkIframeUrl;?>');"><span><span><?php echo $this->__('Place Order') ?></span></span></button>

<script type="text/javascript">
    /*process iframe session expired*/
    var redirectUrl = '<?php echo $updateCartUrl;?>';
    var eventUrlPath = '<?php echo $xpayUrl; ?>';
    Event.observe(window, 'message', function (event) {
        var eventUrl = event.origin;
        if (eventUrl == eventUrlPath) {
            var jsonEventData = JSON.parse(event.data)
            if (jsonEventData.message = "paymentFormSubmitError") {
                if (jsonEventData.params.type != undefined && jsonEventData.params.type == "2") {
                    Foobar = function () {
                        this.callBack = function () {
                            window.location.replace(redirectUrl);
                        };
                    }
                    Foobar.prototype = {
                        Init: function () {
                            var self = this;
                            var errorMessage = jsonEventData.params.error+ " (X-Payments)";
                            alert(errorMessage);
                            self.callBack.call();

                        }
                    };
                    var foobar = new Foobar();
                    foobar.Init();
                }
            }
        }
    });
</script>




