<?php
// vim: set ts=2 sw=2 sts=2 et:

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Qualiteam Software <info@x-cart.com>
 * @category   Cdev
 * @package    Cdev_XPaymentsConnector
 * @copyright  (c) 2010-present Qualiteam software Ltd <info@x-cart.com>. All rights reserved
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Iframe block at checkout on the payment step
 *
 * @see Cdev_XPaymentsConnector_Block_Form_Cc
 */
?>
<?php if ($this->isVisible()): ?>

  <div id="payment-form-<?php echo $this->getMethodCode(); ?>" class="payment-form-xpayments">
    <iframe id="xp-iframe-<?php echo $this->getMethodCode(); ?>" class="xp-iframe" src="" name="xp-iframe-<?php echo $this->getMethodCode(); ?>"></iframe>
  </div>

  <script type="text/javascript">
  //<![CDATA[
    document.fire('xpc:checkoutChanged');
  //]]>
  </script>

<?php endif; ?>
