<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Valerii Demidov
 * @category   Cdev
 * @package    Cdev_XPaymentsConnector
 * @copyright  (c) Qualiteam Software Ltd. <info@qtmsoft.com>. All rights reserved.
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see Cdev_XPaymentsConnector_Block_Form_Cc
 */
?>
<?php
    $_code=$this->getMethodCode();
    $useIframe = Mage::getStoreConfig('payment/xpayments/use_iframe');
    $isRecuringProduct = Mage::helper("xpaymentsconnector")->checkIsRecurringOrder();
    $IsSaveCardsPaymentActive = (bool)Mage::getStoreConfig('payment/savedcards/active');
?>
<?php if (!$useIframe): ?>
    <?php if (!$isRecuringProduct): ?>
        <?php if ($IsSaveCardsPaymentActive): ?>
            <ul id="payment_form_<?php echo $_code ?>" style="display:none;">
                <li>
                <span class="input-box">
                    <input type="checkbox"
                           title="<?php echo $this->__("I want to save a credit card for my future orders in this shop"); ?>"
                           class="checkbox x-payment-card " id="<?php echo $_code . "_" . "save_card" ?>"
                           name="savecard" value="1"/>
                    <label
                        for="<?php echo $_code . "_" . "save_card" ?>"><?php echo $this->__("I want to save a credit card for my future orders in this shop"); ?></label>
                </span>
                </li>
            </ul>
        <?php endif; ?>
    <?php else: ?>
        <ul id="payment_form_<?php echo $_code ?>" style="display:none;">
            <li>
                <span class="input-box">
                    <?php echo $this->__("Your credit card will be saved for this subscription."); ?>
                </span>
            </li>
        </ul>
    <?php endif; ?>
<?php endif; ?>


