<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Valerii Demidov
 * @category   Cdev
 * @package    Cdev_XPaymentsConnector
 * @copyright  (c) Qualiteam Software Ltd. <info@qtmsoft.com>. All rights reserved.
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Additional settings for "IFrame" variant of payment method (frontend)
 *
 * @see Cdev_XPaymentsConnector_Block_Checkout_Onepage_Settings
 */
?>

<?php
$xpHelper = Mage::helper("xpaymentsconnector");
$useIframe = Mage::getStoreConfig('payment/xpayments/use_iframe');
$isRecuringProduct = $xpHelper->checkIssetRecurringOrder();
$IsSaveCardsPaymentActive = (bool)Mage::getStoreConfig('payment/savedcards/active');
$displayOnPaymentStep = (bool)(Mage::getStoreConfig('payment/xpayments/placedisplay') == "review");
?>

<?php if($this->isXpaymentMethod() && $useIframe && $displayOnPaymentStep):?>
    <?php
    $iFrameUrl  = $xpHelper->getIframeUrl();
    $isNeedToSaveUserCard = $xpHelper->isNeedToSaveUserCard();
    $customerRegistered = $xpHelper->isRegisteredUser();
    ?>
    <div id="xpayment-iframe-block">
      <iframe id="xp-iframe" class="xp-iframe" data-src="<?php echo $iFrameUrl;?>" src="<?php echo $iFrameUrl;?>" name="xp-iframe">
      </iframe>
       <?php if($customerRegistered):?>
           <?php if(!$isRecuringProduct["isset"]): ?>
               <?php if ($IsSaveCardsPaymentActive): ?>
                    <span id="iframe-save-card-switcher" >
                                <input type="checkbox" <?php echo ($isNeedToSaveUserCard)?"checked":"";?> title="<?php echo $this->__("Use this credit card"); ?>" class="checkbox x-payment-card " id="iframe_savecard" name="iframe_savecard" value="1" />
                                <label for="iframe_savecard"><?php echo $this->__("I want to use this credit card for my future orders in this shop."); ?></label>
                    </span>
                     <script type="text/javascript">
                       var url = "<?php echo Mage::getUrl("xpaymentsconnector/processing/saveusercard");?>";
                       $('iframe_savecard').observe('change',
                           function() {
                               if($('iframe_savecard').checked === true) {
                                   new Ajax.Request(url, {
                                       parameters: "user_card_save=1"
                                   });
                               }else{
                                   new Ajax.Request(url, {
                                       parameters: "user_card_save=0"
                                   });
                               }
                           });
                     </script>
               <?php endif; ?>
           <?php else: ?>
              <span id="iframe-save-card-switcher" >
                  <?php echo $this->__("Your credit card will be saved for this subscription."); ?>
              </span>
           <?php endif;?>
        <?php endif;?>
    </div>
<?php endif;?>


