<?php
// vim: set ts=2 sw=2 sts=2 et:
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Qualiteam Software <info@x-cart.com>
 * @category   Cdev
 * @package    Cdev_XPaymentsConnector
 * @copyright  (c) 2010-present Qualiteam software Ltd <info@x-cart.com>. All rights reserved
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see Cdev_XPaymentsConnector_Block_Adminhtml_Settings_Tab_PaymentMethods
 */
?>

<form action="<?php echo $this->escapeUrl($this->getUrl('adminhtml/settings_xpc/paymentmethods')); ?>" method="post" name="update_form" id="payment-methods-form">
  <?php echo $this->getBlockHtml('formkey'); ?>
  <input type="hidden" name="mode" value="" id="payment-method-form-mode" />

  <div class="grid">
    <table cellpadding="5" cellspacing="1">

      <tr class="headings">
        <th></th>
        <th><?php echo $this->__('Payment method'); ?></th>
        <th class="currency"><?php echo $this->__('Currency'); ?></th>
        <?php if ($this->isCanSaveCards()): ?>
          <th class="save-cards"><?php echo $this->__('Save cards'); ?></th>
        <?php endif; ?>
      </tr>

      <?php foreach ($this->getPaymentMethods() as $pm): ?>
        <tr class="<?php echo $pm['active_checkbox']['class']; ?>">
          <td class="active">
            <?php $this->printCheckbox($pm['active_checkbox']); ?>
          </td>
          <td <?php if (!$pm['confid']): ?>colspan="<?php echo $this->isCanSaveCards() ? '3' : '2'; ?>3"<?php endif; ?>>
            <label for="<?php echo $pm['active_checkbox']['id']; ?>">
              <?php echo $pm['name']; ?>
            </label>
          </td>
          <?php if ($pm['confid']): ?>
            <td class="currency"><?php echo $pm['currency']; ?></td>
            <?php if ($this->isCanSaveCards()): ?>
              <td class="save-cards">
                <?php if ('Y' == $pm['can_save_cards']): ?>
                  <?php $this->printCheckbox($pm['savecard_checkbox']); ?>
                <?php endif; ?>
              </td>
            <?php endif; ?>
          <?php endif; ?>
        </tr>
      <?php endforeach; ?>

    </table>
  </div>

  <?php foreach ($this->getPaymentMethods(false) as $pm): ?>
    <div class="entry-edit" style="display: none;" id="<?php echo $pm['payment_method']['id']; ?>">
      <div class="entry-edit-head">
        <h4><?php echo $pm['name']; ?></h4>
      </div>
      <fieldset>
        <table cellspacing="0" class="form-list">

          <tr>
            <td class="label"><?php echo $this->__('Title'); ?></td>
            <td class="value">
              <?php $this->printInputText($pm['payment_method']['title']); ?>
            </td>
          </tr>

          <tr>
            <td class="label"><?php echo $this->__('Use forced Authorize operation'); ?></td>
            <td class="value">
              <?php $this->printSelectBox($pm['payment_method']['use_authorize']); ?>
              <p class="note">
                <?php echo $this->__('Work only for non recurring product order.'); ?>
              </p>
            </td>
          </tr>

          <tr>
            <td class="label"><?php echo $this->__('Use forced Authorize operation for recurring products'); ?></td>
            <td class="value">
              <?php $this->printSelectBox($pm['payment_method']['use_initialfee_authorize']); ?>
            </td>
          </tr>

          <tr>
            <td class="label"><?php echo $this->__('Sort order'); ?></td>
            <td class="value">
              <?php $this->printInputText($pm['payment_method']['sort_order']); ?>
            </td>
          </tr>

          <tr>
            <td class="label"><?php echo $this->__('Payment from applicable countries'); ?></td>
            <td class="value">
              <?php $this->printSelectBox($pm['payment_method']['allowspecific']); ?>
            </td>
          </tr>

          <tr class="specificcountry hidden">
            <td class="label"><?php echo $this->__('Payment from Specific countries'); ?></td>
            <td class="value">
              <?php $this->printSelectBox($pm['payment_method']['specificcountry']); ?>
            </td>
          </tr>

        </table>
        <?php echo $this->getChildHtml('updateButton'); ?>
      </fieldset>
    </div>
  <?php endforeach; ?>

    <div class="entry-edit" style="display: none;" id="payment-method-savedcards">
      <div class="entry-edit-head">
        <h4><?php echo $this->__('Use saved credit card'); ?></h4>
      </div>
      <fieldset>
        <table cellspacing="0" class="form-list">

          <tr>
            <td class="label"><?php echo $this->__('Title'); ?></td>
            <td class="value">
              <input type="text" name="savedcards_title" value="<?php echo Mage::helper('settings_xpc')->getSavedCardsConfig('title'); ?>" class="input-text"/>
            </td>
          </tr>

          <tr>
            <td class="label"><?php echo $this->__('Sort order'); ?></td>
            <td class="value">
              <input type="text" name="savedcards_sort_order" value="<?php echo Mage::helper('settings_xpc')->getSavedCardsConfig('sort_order'); ?>" class="input-text"/>
            </td>
          </tr>

        </table>
        <?php echo $this->getChildHtml('updateButton'); ?>
      </fieldset>
    </div>


</form>
