<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Valerii Demidov
 * @category   Cdev
 * @package    Cdev_XPaymentsConnector
 * @copyright  (c) Qualiteam Software Ltd. <info@qtmsoft.com>. All rights reserved.
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see Cdev_XPaymentsConnector_Block_Control
 */
?>
<?php if ($this->getRequiremenetsErrors()) { ?>

<h4><?php echo $this->helper('adminhtml')->__('Failed to meet environment requirements'); ?></h4>
<ul>
<?php foreach ($this->getRequiremenetsErrors() as $err) { ?>
<li class="error"><?php echo $this->helper('adminhtml')->__($err); ?></li>
<?php } ?>
</ul>
<br />
<hr />
<br />

<?php } ?>

<?php if ($this->getConfigurationErrors()) { ?>

<h4><?php echo Mage::helper('xpaymentsconnector')->__('Configuration problems'); ?></h4>
<ul>
<?php foreach ($this->getConfigurationErrors() as $err) { ?>
<li class="error">* <?php echo Mage::helper('xpaymentsconnector')->__($err); ?></li>
<?php } ?>
</ul>
    <p><strong>
            <?php echo $this->__('Please, check x-payment settings '); ?>
            <a href="<?php echo $this->getUrl('adminhtml/system_config/edit/section/xpaymentsconnector/'); ?>">
                <?php echo $this->__('here'); ?>.
            </a>
        </strong>
    </p>
<br />
<hr />
<br />
<?php } ?>

<h4><?php echo Mage::helper('xpaymentsconnector')->__('Test module'); ?></h4>

<p><?php echo Mage::helper('xpaymentsconnector')->__("To test the module settings and connection with X-Payments click the button below. If the module is configured properly, a 'Test transaction completed successfully' message will be displayed at the top of the page."); ?></p>

<form action="<?php echo $this->getUrl('xpaymentsconnector/control/test'); ?>" method="post" name="testmodule_form">
 	<?php echo $this->getBlockHtml('formkey'); ?>
	<?php echo $this->getChildHtml('testButton'); ?>
</form>

<br />
<br />

<h4><?php echo Mage::helper('xpaymentsconnector')->__('Import payment methods'); ?></h4>

<p><?php echo Mage::helper('xpaymentsconnector')->__('To be able to use X-Payments payment methods you need to import them from X-Payments first.'); ?></p>

<?php if ($this->isMethodsRequested()) { ?>

<?php echo Mage::helper('xpaymentsconnector')->__('The list of payment configurations imported from X-Payments'); ?>:<br />

<div class="grid">
<table cellpadding="5" cellspacing="1">
	<tr class="headings">
    	<th><?php echo Mage::helper('xpaymentsconnector')->__('Payment method'); ?></th>
        <th><?php echo Mage::helper('xpaymentsconnector')->__('Payment method ID'); ?></th>
        <th><?php echo Mage::helper('xpaymentsconnector')->__('Auth'); ?></th>
        <!--th><?php echo Mage::helper('xpaymentsconnector')->__('Capture'); ?></th>
        <th><?php echo Mage::helper('xpaymentsconnector')->__('Void'); ?></th>
        <th class="last"><?php echo Mage::helper('xpaymentsconnector')->__('Refund'); ?></th-->
	</tr>

<?php foreach($this->getPaymentMethods() as $pm) { ?>

	<tr>
		<td><?php echo $pm['name']; ?></td>
        <td><?php echo $pm['confid']; ?></td>
        <td><?php if ($pm['is_auth']) { ?><?php echo $this->__('Yes'); ?><?php } else { ?><?php echo $this->__('No'); ?><?php } ?></td>
        <!--td><?php if ($pm['is_capture']) { ?><?php echo $this->helper('adminhtml')->__('Yes'); ?><?php } else { ?><?php echo $this->helper('adminhtml')->__('No'); ?><?php } ?></td>
        <td><?php if ($pm['is_void']) { ?><?php echo $this->__('Yes'); ?><?php } else { ?><?php echo $this->__('No'); ?><?php } ?></td>
        <td class="last"><?php if ($pm['is_refund']) { ?><?php echo $this->__('Yes'); ?><?php } else { ?><?php echo $this->__('No'); ?><?php } ?></td-->
  	</tr>

<?php } ?>

</table>
</div>

<form action="<?php echo $this->getUrl('xpaymentsconnector/control/clear'); ?>" method="post" name="clear_form">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <?php echo $this->getChildHtml('clearButton'); ?>
</form>

<?php if ($this->isMethodsAlreadyImported()) { ?>
	<br />
	<br />
	<p><?php echo $this->__('Warning! Importing payment configurations from X-Payments will disable the X-Payments connector payment method!'); ?></p>
<?php } ?>

<?php } ?>

<form action="<?php echo $this->getUrl('xpaymentsconnector/control/request'); ?>" method="post" name="request_form">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <?php echo $this->getChildHtml('requestButton'); ?>
</form>


