<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Valerii Demidov
 * @category   Cdev
 * @package    Cdev_XPaymentsConnector
 * @copyright  (c) Qualiteam Software Ltd. <info@qtmsoft.com>. All rights reserved.
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see Cdev_XPaymentsConnector_Block_Info_Cc
 */
?>
<?php

$order = $this->getInfo()->getMethodInstance()->getOrder();
$orderCardData = array();
if($order){
    $orderCardData = $this->getCardData();
}
?>

<?php echo $this->getMethod()->getTitle(); ?>
<br />
<?php if ($this->getInfo()->getLastTransId() == ''): ?>
    <?php
        echo $this->__('You will be redirected to X-Payments website when you place an order.');
    ?>
<?php else: ?>
    <?php
        echo $this->__('X-Payments Transaction ID: %s', $this->htmlEscape($this->getInfo()->getLastTransId()));
    ?>
    <br/>
<?php endif; ?>
<?php if(!empty($orderCardData)): ?>
    <span id="x-payment-prepaid-card-info">
            <?php echo $this->__('For current order we used your payment card %s', $orderCardData); ?>
    </span>
<?php endif;?>
