<?php
// vim: set ts=2 sw=2 sts=2 et:
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Qualiteam Software <info@x-cart.com>
 * @category   Cdev
 * @package    Cdev_XPaymentsConnector
 * @copyright  (c) 2010-present Qualiteam software Ltd <info@x-cart.com>. All rights reserved
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see Cdev_XPaymentsConnector_Block_Customer_Usercards_List
 */
?>
<div class="page-title">
  <h1><?php echo $this->__('Payment cards') ?></h1>
</div>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('pager'); ?>

<?php if ($this->getCards()->getSize()): ?>
  <form  id="credit-card-list-form" method="post" action="<?php echo $this->escapeUrl($this->getFormUrl()); ?>">

    <table class="data-table" id="my-credit-cards-table">
      <col width="1" />
      <col width="1" />
      <col />
      <col width="1" />
      <col width="1" />
      <thead>
        <tr>
          <th>
            <a id="select-all-cards" href="javascript: void(0);" class="select-all-link"><?php echo $this->__('Select all'); ?></a>
            /
            <a id="unselect-all-cards" href="javascript: void(0);" class="select-all-link unselect"><?php echo $this->__('Unselect all'); ?></a>
          </th>
          <th><?php echo $this->__('Card id #') ?></th>
          <th><?php echo $this->__('Card number') ?></th>
          <th><?php echo $this->__('Usage card type'); ?></th>
          <th><?php echo $this->__('Card type'); ?></th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($this->getCards() as $card): ?>
          <tr>
            <td>
              <input type="checkbox" class="checkbox related-checkbox" value="<?php echo $card->getXpCardId(); ?>" name="card[]" />
            </td>
            <td><?php echo $card->getXpCardId(); ?></td>
            <td><?php echo $this->getCardString($card); ?></td>
            <td><?php echo $this->getCardUsageType($card); ?></td>
            <td>
              <span class="xpc-card-logo-list <?php echo strtolower($card->getCardType()); ?>" title="<?php echo $card->getCardType(); ?>"></span>
            </td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>

    <script type="text/javascript">decorateTable('my-credit-cards-table');</script>

    <?php echo $this->getChildHtml('pager'); ?>

    <div class="buttons-set">
      <p class="back-link">
        <a href="<?php echo $this->escapeUrl($this->getBackUrl()); ?>">
          <small>&laquo;&nbsp;</small><?php echo $this->__('Back') ?>
        </a>
      </p>
      <button class="button" type="submit" title="<?php echo $this->__('Remove'); ?>">
        <span><span><?php echo $this->__('Remove'); ?></span></span>
      </button>
      <?php if (Mage::helper('settings_xpc')->isZeroAuthMethodConfigured()): ?>
        <button class="button" type="button" title="<?php echo $this->__('Add new card'); ?>" onclick="javascript: window.location='<?php echo $this->escapeUrl($this->getAddCardUrl()); ?>'">
          <span><span><?php echo $this->__('Add new card'); ?></span></span>
        </button>
      <?php endif; ?>
    </div>
  </form>
<?php else: ?>

  <p><?php echo $this->__('You have no saved credit cards yet.'); ?></p>
  <div class="buttons-set">
    <p class="back-link">
      <a href="<?php echo $this->escapeUrl($this->getBackUrl()); ?>">
        <small>&laquo;&nbsp;</small><?php echo $this->__('Back') ?>
      </a>
    </p>
    <?php if (Mage::helper('settings_xpc')->isZeroAuthMethodConfigured()): ?>
      <button class="button" type="button" title="<?php echo $this->__('Add new card'); ?>" onclick="javascript: window.location='<?php echo $this->escapeUrl($this->getAddCardUrl()); ?>'">
        <span><span><?php echo $this->__('Add new card'); ?></span></span>
      </button>
    <?php endif; ?>
  </div>

<?php endif; ?>
