<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Valerii Demidov
 * @category   Cdev
 * @package    Cdev_XPaymentsConnector
 * @copyright  (c) Qualiteam Software Ltd. <info@qtmsoft.com>. All rights reserved.
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * X-Payments order state template
 *
 * @see Cdev_XPaymentsConnector_Block_Adminhtml_Sales_Order_View_Tab_Xporderstate
 */
?>

<?php $xpaymentsOrderInfo = $this->getXpaymentsOrderInfo(); ?>
<?php if($xpaymentsOrderInfo["success"]): ?>
    <?php $xpaymentOrderState  = $xpaymentsOrderInfo["info"]["payment"];?>
    <?php $xpaymentOrdertransactionsList  = $xpaymentsOrderInfo["info"]["transactions"]; ?>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4><?php echo $this->__('Transaction list'); ?></h4>
        </div>

            <div class="grid np">
                <div class="hor-scroll">
                    <table cellspacing="0" id="xpayment-transaction-list" class="data order-tables">
                        <colgroup>
                            <col />
                            <col />
                            <col width="1">
                            <col width="1">
                            <col width="1">
                            <col width="1">
                            <col width="1">
                        </colgroup><thead>
                        <tr class="headings">
                            <th><span class="nobr"><?php echo $this->__('Additional info'); ?></span></th>
                            <th><span class="nobr"><?php echo $this->__('Date, time'); ?></span></th>
                            <th><span class="nobr"><?php echo $this->__('Type'); ?></span></th>
                            <th><span class="nobr"><?php echo $this->__('Result payment status'); ?></span></th>
                            <th class="last"><span class="nobr"><?php echo $this->__('Transaction result'); ?></span></th>
                            <th class="last"><span class="nobr"><?php echo $this->__('Total'); ?></span></th>
                        </tr>
                        </thead>
                        <tbody>
                            <?php $rowClass = "odd";?>
                            <?php foreach($xpaymentOrdertransactionsList as $key => $transaction):?>
                                <?php $rowClass = ($key%2==0)?"even":"odd"; ?>
                                <tr class="border pointer <?php echo $rowClass?>">
                                    <td>
                                        <div class="item-container" >
                                            <table cellspacing="0" class="form-list">
                                                <tbody>
                                                <?php foreach($transaction["fields"] as $field): ?>
                                                    <tr>
                                                        <td class="label"><label><?php echo $field["name"]?></label></td>
                                                        <td class="value"><strong><?php echo $field["value"]?></strong></td>
                                                    </tr>
                                                <?php endforeach; ?>
                                                </tbody>
                                            </table>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="item-container">
                                            <div class="item-text">
                                                <strong>
                                                    <?php echo date("M d,Y  H:i:s",$transaction["date"]);?>
                                                </strong>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="a-center">
                                        <span class="price">
                                            <strong>
                                                <?php echo $transaction["action"];?>
                                            </strong>
                                        </span></td>
                                    <td class="a-center">
                                        <span class="price">
                                            <?php echo $transaction["payment_status"];?>
                                        </span>
                                    </td>
                                    <td class="a-center">
                                        <span class="price">
                                            <?php echo $transaction["status"];?>
                                        </span>
                                    </td>
                                    <td class="a-center">
                                        <span class="price">
                                            <strong>
                                                <?php echo $transaction["total"];?>
                                            </strong>
                                        </span>
                                    </td>
                                </tr>
                            <?php endforeach;?>
                        </tbody>
                    </table>
                </div>
            </div>
    </div>

    <p>
    <br />
    <br />
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4><?php echo $this->__('Order state'); ?></h4>
        </div>

        <div class="grid">
            <div class="hor-scroll">
                <table cellspacing="0" class="data order-tables">
                    <colgroup><col>
                        <col width="1">
                        <col width="1">
                        <col width="1">
                        <col width="1">
                    </colgroup><thead>
                    <tr class="headings">
                        <th><span class="nobr"><?php echo $this->__('Amount'); ?></span></th>
                        <th><span class="nobr"><?php echo $this->__('Authorized'); ?></span></th>
                        <th><span class="nobr"><?php echo $this->__('Captured'); ?></span></th>
                        <th class="last"><span class="nobr"><?php echo $this->__('Refunds'); ?></span></th>
                    </tr>
                    </thead>
                    <tbody class="even">
                    <tr class="border">
                        <td>
                            <div class="item-container" id="order_item_446">
                                <div class="item-text">
                                    <?php if(!empty($xpaymentOrderState["message"])): ?>
                                        <h5 class="title">
                                                <span id="order_title">
                                                    <?php echo $this->__($xpaymentOrderState["message"]);?>
                                                </span></h5>
                                    <?php endif;?>
                                    <span class="price">
                                            <?php echo Mage::helper('core')->currency($xpaymentOrderState["amount"], true, false);?>
                                        </span>
                                </div>
                            </div>
                        </td>
                        <td class="a-center">
                                <span class="price">
                                    <?php echo Mage::helper('core')->currency($xpaymentOrderState["authorized"], true, false);?>
                                </span></td>
                        <td class="a-center">
                                <span class="price">
                                    <?php echo Mage::helper('core')->currency($xpaymentOrderState["capturedAmount"], true, false);?>
                                </span>
                        </td>
                        <td class="a-center">
                                <span class="price">
                                    <?php echo Mage::helper('core')->currency($xpaymentOrderState["refundedAmount"], true, false);?>
                                </span>
                        </td>
                    </tr>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
    </p>

<?php  else: ?>
    <?php echo $xpaymentsOrderInfo["error_message"];?>
<?php endif;?>