<?php
// vim: set ts=2 sw=2 sts=2 et:
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Qualiteam Software <info@x-cart.com>
 * @category   Cdev
 * @package    Cdev_XPaymentsConnector
 * @copyright  (c) 2010-present Qualiteam software Ltd <info@x-cart.com>. All rights reserved
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * X-Payments order state template
 *
 * @see Cdev_XPaymentsConnector_Block_Adminhtml_Sales_Order_View_Tab_Xporderstate
 */
?>

<?php if ($this->getError()): ?>
  <ul class="messages">
    <li class="error-msg">
      <?php echo $this->__($this->getError()); ?>
    </li>
  </ul>
<?php endif; ?>


<?php foreach ($this->getTransactions() as $orderId => $orderTransactions): ?>

  <div class="entry-edit">

    <div class="entry-edit-head xp-transaction-head-block pointer">
      <h4><?php echo $this->__('Transaction list for order %s', $orderId); ?></h4>
      <span class="transaction-accordion">
        <span class="transaction-down" >
          <img src="<?php echo $this->getArrowImg('down'); ?>">
        </span>
        <span class="transaction-up" style="display: none">
          <img src="<?php echo $this->getArrowImg('up'); ?>">
        </span>
      </span>
    </div>

    <div class="grid np" style="display: none">
      <div class="hor-scroll">

        <?php if (!empty($orderTransactions)): ?>

          <table cellspacing="0" id="xpayment-transaction-list" class="data order-tables">

            <thead>
              <tr class="headings">
                <th><span class="nobr"><?php echo $this->__('Transaction ID'); ?></span></th>
                <th><span class="nobr"><?php echo $this->__('Date, time'); ?></span></th>
                <th class="a-center"><span class="nobr"><?php echo $this->__('Amount'); ?></span></th>
                <th class="a-center"><span class="nobr"><?php echo $this->__('Type'); ?></span></th>
                <th class="a-center"><span class="nobr"><?php echo $this->__('Result payment status'); ?></span></th>
                <th class="a-center"><span class="nobr"><?php echo $this->__('Transaction result'); ?></span></th>
                <th><span class="nobr last"><?php echo $this->__('Additional info'); ?></span></th>
              </tr>
            </thead>

            <tbody>
              <?php foreach($orderTransactions as $key => $transaction): ?>
                <tr class="border pointer <?php echo $this->getRowClass($key); ?>">

                  <td>
                    <span class="price">
                      <strong><?php echo $this->__($transaction['txnid']); ?></strong>
                    </span>
                  </td>

                  <td>
                    <div class="item-container">
                      <div class="item-text nobr" title="<?php echo $this->getTransactionDateTime($transaction); ?>">
                        <?php if (!empty($transaction['date'])): ?>
                          <strong><?php echo $this->getTransactionDate($transaction); ?></strong>
                          <?php echo $this->getTransactionTime($transaction); ?>    
                        <?php else: ?>
                          <i><?php echo $this->__('Unknown'); ?></i>
                        <?php endif; ?>
                      </div>
                    </div>
                  </td>

                  <td class="a-center">
                    <span class="price">
                      <strong><?php echo $this->__($transaction['total']); ?></strong>
                    </span>
                  </td>

                  <td class="a-center">
                    <span class="price">
                      <strong><?php echo $this->__($transaction['action']); ?></strong>
                    </span>
                  </td>
                  
                  <td class="a-center">
                    <span class="price">
                      <?php echo $this->__($transaction['payment_status']); ?>
                    </span>
                  </td>
                  
                  <td class="a-center">
                    <span class="price">
                      <?php echo $this->__($transaction['status']); ?>
                    </span>
                  </td>
                  
                  <td>
                    <div class="item-container" >
                      <?php if (!empty($transaction['fields'])): ?>
                        <table cellspacing="0" class="form-list">
                          <?php foreach($transaction['fields'] as $field): ?>
                            <tr>
                              <td class="label"><label><?php echo $field['name']; ?></label></td>
                              <td class="value"><strong><?php echo $field['value']; ?></strong></td>
                            </tr>
                          <?php endforeach; ?>
                        </table>
                      <?php endif; ?>
                    </div>
                  </td>

                </tr>
              <?php endforeach; ?>
            </tbody>

          </table>

        <?php else: /* if (!empty($orderTransactions)): */ ?>

          <?php echo $this->__('No payment transactions for this order'); ?>

        <?php endif; /* if (!empty($transactions)): */ ?>

      </div> <!-- class="hor-scroll" -->
    </div> <!-- class="grid np" -->

  </div> <!-- class="entry-edit" -->

  <br />

<?php endforeach; /* foreach ($this->getTransactions() as $orderId => $orderTransactions): */ ?>


<?php foreach ($this->getOrderData() as $orderId => $data): ?>

  <div class="entry-edit">
    <div class="entry-edit-head">
      <h4><?php echo $this->__('Order(s) state'); ?></h4>
    </div>

    <div class="grid">
      <div class="hor-scroll">

        <?php if (!empty($data)): ?>
        
          <table cellspacing="0" class="data order-tables">

            <thead>
              <tr class="headings">
                <th><span class="nobr"><?php echo $this->__('Order ID'); ?></span></th>
                <th><span class="nobr"><?php echo $this->__('Payment status'); ?></span></th>  
                <th class="a-center"><span class="nobr"><?php echo $this->__('Amount'); ?></span></th>
                <th class="a-center"><span class="nobr"><?php echo $this->__('Authorized'); ?></span></th>
                <th class="a-center"><span class="nobr"><?php echo $this->__('Captured'); ?></span></th>
                <th class="a-center"><span class="nobr"><?php echo $this->__('Refunds'); ?></span></th>
                <th class="last"><span class="nobr"><?php echo $this->__('Actions'); ?></span></th>
              </tr>
            </thead>

            <tbody>
              <tr class="border">

                <td>
                  <div class="item-text"><?php echo $orderId; ?></div>
                </td>

                <td>
                  <div class="item-container">
                    <div class="item-text nobr">
                      <?php if (!empty($data['message'])): ?>
                        <strong><?php echo $this->__($data['message']); ?></strong>
                      <?php else: ?>
                        <strong><?php echo $this->__('Unknown'); ?></strong>
                      <?php endif; ?>
                    </div>
                  </div>
                </td>

                <td class="a-center">
                  <div class="item-container">
                    <div class="item-text">
                      <span class="price">
                        <?php echo Mage::helper('core')->currency($data['amount'], true, false); ?>
                      </span>
                    </div>
                  </div>
                </td>

                <td class="a-center">
                  <span class="price">
                    <?php if ($data['authorized'] > 0): ?>
                      <?php echo Mage::helper('core')->currency($data['authorized'], true, false); ?>
                    <?php endif; ?>
                  </span>
                </td>
              
                <td class="a-center">
                  <span class="price">
                    <?php if ($data['capturedAmount'] > 0): ?>
                      <?php echo Mage::helper('core')->currency($data['capturedAmount'], true, false); ?>
                    <?php endif; ?>
                  </span>
                </td>
              
                <td class="a-center">
                  <span class="price">
                    <?php if ($data['refundedAmount'] > 0): ?>
                      <?php echo Mage::helper('core')->currency($data['refundedAmount'], true, false); ?>
                    <?php endif; ?>
                  </span>
                </td>
              
                <td>
                  <div class="item-text">
                    <form method="post" id="<?php echo $this->getFormId($orderId); ?>" class="xp_fast_transactions" action="<?php echo $this->escapeUrl($this->getFormUrl()); ?>">

                      <input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>" />
                      <input type="hidden" name="orderid" value="<?php echo $orderId; ?>" />
                      <input type="hidden" name="xpc_txnid" value="<?php echo $data['xpc_txnid']; ?>" />
                      <input type="hidden" name="xpc_action" class="xpc_action" value="" />
                      <input type="text" name="transaction_amount" value="<?php echo $this->getActionAmount($orderId); ?>" class="<?php echo $this->getAmountInputClass($orderId); ?>" />

                      <?php if ($data['capturedAmountAvail'] > 0): ?>
                        <input type="button" name="capture" value="Capture" class="form-button xp-transaction-submit" onclick="<?php echo $this->getOnClick('capture', $orderId); ?>" />
                        </br>
                      <?php endif; ?>

                      <?php if ($data['voidedAmountAvail'] > 0): ?>
                        <input type="button" name="void" value="<?php echo $this->getVoidValue($data); ?>" class="form-button xp-transaction-submit" onclick="<?php echo $this->getOnClick('void', $orderId, $data['voidedAmountAvail']); ?>" /> 
                      <?php endif; ?>

                      <?php if ($data['refundedAmountAvail'] > 0): ?>
                        <input type="button" name="refund" value="Refund" class="form-button" onclick="<?php echo $this->getOnClick('refund', $orderId); ?>" />
                      <?php endif; ?>

                    </form>
                  </div>
                </td>

              </tr>
            </tbody>

          </table>

        <?php else: /* if (!empty($orderData)): */ ?>

          <?php echo $this->__('No payment data for this order'); ?>

        <?php endif; /* if (!empty($orderData)): */ ?>

      </div> <!-- class="hor-scroll" -->
    </div> <!-- class="grid" -->

  </div> <!-- class="entry-edit" -->

<?php endforeach; /* foreach ($this->getOrderData() as $orderId => $orderData): */ ?>


<?php foreach ($this->getFraudCheckData() as $data): ?>
<div class="entry-edit">
  <div class="entry-edit-head">
    <h4><?php echo $this->__($data->getData('service')); ?></h4>
  </div>
  <div class="fieldset">
    <table cellspacing="0" class="form-list">
      <tr>
        <td class="label"><?php echo $this->__('Result'); ?></td>
        <td class="value">
          <?php if ('1' == $data->getData('result')): ?>
            <strong><?php echo $this->__('Antifraud check passed'); ?></strong>
          <?php elseif ('2' == $data->getData('result') && 'nofraud' == $data->getData('code')): ?>
            <strong><?php echo $this->__('Being Reviewed by NoFraud'); ?></strong>
          <?php elseif ('2' == $data->getData('result')): ?>
            <strong><?php echo $this->__('Manual Review required'); ?></strong>
          <?php elseif ('3' == $data->getData('result')): ?>
            <strong><?php echo $this->__('High fraud risk detected'); ?></strong>
          <?php else: ?>
            <strong><?php echo $this->__('Unknown'); ?></strong>          
          <?php endif; ?>
        </td>
      </td>
      <tr>
        <td class="label"><?php echo $this->__('Status'); ?></td>
        <td class="value"><strong><?php echo $data->getData('status'); ?></strong></td>
      </td>
      <?php if ($data->getData('score')): ?>
        <tr>
          <td class="label"><?php echo $this->__('Score'); ?></td>
          <td class="value"><strong><?php echo $data->getData('score'); ?></strong></td>
        </td>      
      <?php endif; ?>
      <?php if ($data->getData('transaction_id')): ?>
        <tr>
          <td class="label"><?php echo $this->__('Transaction ID'); ?></td>
          <td class="value">
            <?php if ($data->getData('url')): ?>
              <strong><a href="<?php echo $this->escapeUrl($data->getData('url')); ?>" target="_blank"><?php echo $data->getData('transaction_id'); ?></a></strong>
            <?php else: ?>
              <strong><?php echo $data->getData('transaction_id'); ?></strong>
            <?php endif; ?>
          </td>
        </td>
      <?php endif; ?>
      <?php if ($data->getData('rules')): ?>
        <tr>
          <td class="label"><?php echo $this->__('Triggered rules'); ?></td>
          <td class="value">
            <ul>
              <?php foreach ($data->getRulesList() as $rule): ?>
                <li><?php echo $rule; ?></li>
              <?php endforeach; ?>
            </ul>
          </td>
        </td>
      <?php endif; ?>
      <?php if ($data->getData('errors')): ?>
        <tr>
          <td class="label"><?php echo $this->__('Errors'); ?></td>
          <td class="value">
            <ul>
              <?php foreach ($data->getErrorsList() as $error): ?>
                <li><?php echo $error; ?></li>
              <?php endforeach; ?>
            </ul>
          </td>
        </td>
      <?php endif; ?>
      <?php if ($data->getData('warnings')): ?>
        <tr>
          <td class="label"><?php echo $this->__('Warnings'); ?></td>
          <td class="value">
            <ul>
              <?php foreach ($data->getWarningsList() as $warning): ?>
                <li><?php echo $warning; ?></li>
              <?php endforeach; ?>
            </ul>
          </td>
        </td>
      <?php endif; ?>
    </table>
  </div>
</div>
<?php endforeach; ?>

<?php if ($this->isPaymentRequired()): ?>  

  <div class="entry-edit">
    <div class="entry-edit-head">
      <h4><?php echo $this->__('Backend order'); ?></h4>
    </div>

    <div class="fieldset">
      <?php echo $this->__('This order is not payed.'); ?>
      <a href="<?php echo $this->escapeUrl($this->getBackendPaymentUrl()); ?>"><?php echo $this->__('Go to the payment page'); ?></a>
    </div>

  </div>

<?php endif; ?>
