<?php
// vim: set ts=2 sw=2 sts=2 et:
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Qualiteam Software <info@x-cart.com>
 * @category   Cdev
 * @package    Cdev_XPaymentsConnector
 * @copyright  (c) 2010-present Qualiteam software Ltd <info@x-cart.com>. All rights reserved
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * X-Payments payment form for add new card in backend
 *
 * @see Cdev_XPaymentsConnector_Block_Adminhtml_Usercards_Iframe
 */
?>

<?php if ($this->getError()): ?>

  <script type="text/javascript">
  //<![CDATA[
    var msg = {
      message: 'paymentFormSubmitError',
        params: {
          height: 0,
          error: '<?php echo addslashes($this->__($this->getError())); ?>',
          type: 1
        }
     };
     window.parent.postMessage(JSON.stringify(msg), '*');
  //]]>
  </script>

<?php elseif ($this->isReturn()): ?>

  <script type="text/javascript">
  //<![CDATA[
     window.parent.location.href = "<?php echo $this->escapeUrl($this->getPaymentCardsUrl()); ?>";
  //]]>
  </script>

<?php else: ?>

  <form id="xpc-form-redirect" action="<?php echo $this->getFormAction(); ?>" method="post">
    <?php foreach ($this->getFields() as $name => $value): ?>
      <input type="hidden" name="<?php echo $name; ?>" value="<?php echo $value; ?>" />
    <?php endforeach; ?>
  </form>

  <script type="text/javascript">
  //<![CDATA[
    var paymentform = document.getElementById('xpc-form-redirect');
    window.onload = function() {
      paymentform.submit();
    }
  //]]>
  </script>

<?php endif; ?>
