<?php
// vim: set ts=2 sw=2 sts=2 et:
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Qualiteam Software info@qtmsoft.com
 * @category   Cdev
 * @package    Cdev_XPaymentsConnector
 * @copyright  (c) 2010-2016 Qualiteam software Ltd <info@x-cart.com>. All rights reserved
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see Cdev_XPaymentsConnector_Block_Adminhtml_Settings_Xpc
 */
?>
<?php if ($this->getRequiremenetsErrors()): ?>

  <h4><?php echo $this->__('Failed to meet environment requirements'); ?></h4>
  
  <ul>
    <?php foreach ($this->getRequiremenetsErrors() as $err): ?>
      <li class="error">
        <?php echo $this->__($err); ?>
      </li>
    <?php endforeach; ?>
  </ul>

  <br/>

<?php endif; ?>

<div class="xpayment-info">

  <div class="content-header">
    <table cellspacing="0">
    <tr>
      <td><h3><?php echo $this->__('X-Payments Connector'); ?></h3></td>
    </tr>
    </table>
  </div>

  <?php if ($this->getConfigurationErrors()): ?>

    <h4 class="sub-heading">
      <?php echo $this->__('X-Payments Connector is not configured yet. Please, check'); ?>
      <a href="<?php echo $this->getSystemConfigXpcUrl(); ?>" target="_blank"><?php echo $this->__('settings') ?></a>
    </h4>

    <div class="payment-description">

      <div class="payment-logo">
        <img src="<?php echo Mage::getBaseUrl('js') . 'xpayment/images/xpayment-logo.png'; ?>" alt="X-Payments Connector"/>
      </div>

      <div class="description-block">
        <p>
          <?php echo $this->getDescription(); ?>
        </p>
      </div>

    </div>

    <h4>
      <?php echo $this->__('Connect to X-Payments in 3 easy steps:'); ?>
    </h4>

    <div class="payment-step">

      <div class="step">
        <span class="step-number">1</span>
        <p>
          <?php echo $this->__('Open your'); ?>
          <a href="<?php echo $this->getTrialDemoUrl(); ?>" target="_blank"><?php echo $this->__('X-Payments'); ?></a>
          <?php echo $this->__('back-end (if you do not have it)'); ?>
        </p>
        <button onclick="javascript: window.open('<?php echo $this->getTrialDemoUrl(); ?>');">
          <?php echo $this->__('Start free Trial'); ?>
        </button>
      </div>
      
      <img src="<?php echo Mage::getBaseUrl('js') . 'xpayment/images/atep-arrow.png' ?>" class="step-arrow">

      <div class="step">
        <span class="step-number">2</span>
        <p>
          <?php echo $this->__('Configure payment methods at'); ?>
          <strong style="white-space: nowrap;"><?php echo $this->__('X-Payments'); ?></strong>
        </p>
        <a href="<?php echo $this->getUserManualUrl(); ?>" target="_blank"><?php echo $this->__('Read how to do that'); ?></a>
      </div>

      <img src="<?php echo Mage::getBaseUrl('js') . 'xpayment/images/atep-arrow.png' ?>" class="step-arrow">

      <div class="step">
        <span class="step-number">3</span>
        <p>
          <?php echo $this->__('Connect'); ?>
          <strong><?php echo $this->__('X-Payments'); ?></strong>
          <?php echo $this->__('with'); ?>
          <strong><?php echo $this->__('Magento'); ?></strong>
        </p>
        <a href="<?php echo $this->getUserVideoUrl(); ?>" target="_blank"><?php echo $this->__('See how to do that'); ?></a>
      </div>

    </div>

    <hr/>

  <?php endif; ?>

</div>

<br/>

<h4><?php echo $this->__('Import payment methods'); ?></h4>

<p><?php echo $this->__('To be able to use X-Payments payment methods you need to import them from X-Payments first.'); ?></p>

<?php if ($this->isMethodsRequested()) { ?>

    <?php echo $this->__('The list of payment configurations imported from X-Payments'); ?>:<br/>

    <div class="grid">
        <table cellpadding="5" cellspacing="1">
            <tr class="headings">
                <th><?php echo $this->__('Payment method'); ?></th>
                <th><?php echo $this->__('Payment method ID'); ?></th>
                <th><?php echo $this->__('Auth'); ?></th>
            </tr>

            <?php foreach ($this->getPaymentMethods() as $pm) { ?>

                <tr>
                    <td><?php echo $pm['name']; ?></td>
                    <td><?php echo $pm['confid']; ?></td>
                    <td><?php if ($pm['is_auth']) { ?><?php echo $this->__('Yes'); ?><?php } else { ?><?php echo $this->__('No'); ?><?php } ?></td>
                </tr>

            <?php } ?>

        </table>
    </div>

    <form action="<?php echo $this->getUrl('adminhtml/settings_xpc/clear'); ?>" method="post" name="clear_form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <?php echo $this->getChildHtml('clearButton'); ?>
    </form>

    <?php if ($this->isMethodsAlreadyImported()) { ?>
        <br/>
        <br/>
        <p><?php echo $this->__('Warning! Importing payment configurations from X-Payments will disable the X-Payments connector payment method!'); ?></p>
    <?php } ?>

<?php } ?>

<form action="<?php echo $this->getUrl('adminhtml/settings_xpc/request'); ?>" method="post" name="request_form">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <?php echo $this->getChildHtml('requestButton'); ?>
</form>

<br/>
<br/>
<h4>
    <?php echo $this->__('Need help in settings of X-Payments?'); ?>
    <a href="<?php echo $this->getContactUsUrl(); ?>" target="_blank"><?php echo $this->__('Contact us!'); ?></a>
</h4>
