<?php
// vim: set ts=2 sw=2 sts=2 et:
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @author     Qualiteam Software <info@x-cart.com>
 * @category   Cdev
 * @package    Cdev_XPaymentsConnector
 * @copyright  (c) 2010-present Qualiteam software Ltd <info@x-cart.com>. All rights reserved
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * @see Cdev_XPaymentsConnector_Block_Adminhtml_Settings_Xpc
 */
?>

<div class="content-header">
  <table cellspacing="0">
    <tr>
      <td style="width:50%;"><h3><?php echo $this->__('X-Payments Connector'); ?></h3></td>
      <td class="form-buttons"<?php if (!$this->isShowStickyPanel()): ?> style="display: none;"<?php endif; ?>>
        <?php if (!$this->isWelcomeMode()): ?>
          <?php echo $this->getChildHtml('updateButton'); ?>
          <?php echo $this->getChildHtml('importButton'); ?>
          &nbsp;
          <a href="<?php echo $this->escapeUrl($this->getAddNewPaymentMethodUrl()); ?>" target="_blank"><?php echo $this->__('Add payment method'); ?></a>
        <?php endif; ?>
      </td>
    </tr>
  </table>
</div>

<div id="settings_xpc">
  
  <?php if ($this->isWelcomeMode()): ?>
    <div id="settings_xpc_tabs_welcome_section_content">
      <?php echo $this->getChildHtml('welcomeSection'); ?>
    </div>
  <?php endif; ?>

  <div id="settings_xpc_tabs_connection_section_content">
    <?php echo $this->getChildHtml('connectionSection'); ?>
  </div>

  <?php if (!$this->isWelcomeMode()): ?>
    <div id="settings_xpc_tabs_paymentmethods_section_content">
      <?php echo $this->getChildHtml('paymentMethodsSection'); ?>
    </div>
    <?php if ($this->isCanSaveCards()): ?>
      <div id="settings_xpc_tabs_zeroauth_section_content">
        <?php echo $this->getChildHtml('zeroAuthSection'); ?>
      </div>
    <?php endif; ?>
  <?php endif; ?>
  
</div>

<script type="text/javascript">
  var MAX_SLOTS = <?php echo Cdev_XPaymentsConnector_Helper_Settings_Data::MAX_SLOTS; ?>;
</script>
